### ISSUE TITLE
Compatibility Issue: PEFT and BitsAndBytesConfig with Liger Kernel. Seeking Alternatives for Quantization and LoRA Fine-Tuning.

### ISSUE THREAD

**Issue by GianottiGustavo** [linkedin/Liger-Kernel#235]
### 🐛 Describe the bug

Hi everyone,

I have been trying to use PEFT with BitsAndBytesConfig iwith AutoLigerKernelForCausalLM.from_pretrained. However, I keep encountering type errors during training.
"RuntimeError: self and mat2 must have the same dtype, but got Half and Float"

I tried my own quantization with BitsAndBytes, and also using someone else's quantizated model. With both cases I get the same error.

Could anyone clarify if PEFT and BitsAndBytesConfig are officially supported with the Liger kernel? If they are, could you provide any specific guidance or documentation references that might help resolve these type errors?
If not, any advise for quantization and lora finetuning?

THX!

### Reproduce

```
model = AutoLigerKernelForCausalLM.from_pretrained("PrunaAI/Qwen-Qwen2-0.5B-Instruct-bnb-4bit-smashed", 
                                                   low_cpu_mem_usage=True, device_map={"":0})

lora_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0,
    r=128,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "down_proj",
        "up_proj",
    ],
    use_rslora=False,
    loftq_config=None,
)

model = get_peft_model(model, lora_config)

sft_config = SFTConfig(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        # num_train_epochs=1,  # We manage epochs manually
        max_steps=30,  # Add chunk size to the current step
        learning_rate=2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps=50,
        optim="adamw_8bit", # grokadamw, pip install grokadamw. other is paged_adamw_8bit.
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir=folder_model_path + "outputs",
        logging_dir=folder_model_path + "logs",
        save_strategy="steps",
        save_steps=50,
        max_seq_length=max_seq_length,
        dataset_text_field="text",
        dataset_num_proc=2,
    )
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    packing=False,  # Can make training faster for short sequences.
    args=sft_config,
    peft_config=lora_config,
)
trainer_stats = trainer.train()
```

### Versions

Environment Report:
-------------------
Operating System: Linux-6.2.0-39-generic-x86_64-with-glibc2.37
Python version: 3.11.9
PyTorch version: 2.4.1+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.45.0.dev0

**Comment by GianottiGustavo** [comment]
Hey @Tcc0403, thanks for the help! I’m encountering the same error with your script.

I’m using an NVIDIA 1060 (aware that it doesn't have enough VRAM for the model), but the issue persists. Could this be related to the Pascal architecture?

Could you please share your pip freeze output or confirm the bitsandbytes version you're using?

Here's the environment I set up:

**Environment Report:**
-------------------
Operating System: Linux-6.2.0-39-generic-x86_64-with-glibc2.37
Python version: 3.10.12
PyTorch version: 2.4.0+cu121
CUDA version: 12.1
Triton version: 3.0.0
Transformers version: 4.44.2

**Installed packages:**
liger-kernel==0.2.1
accelerate==0.34.2
bitsandbytes==0.43.3
fsspec==2024.6.1
trl==0.10.1

**NVIDIA-related packages:**
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.1.105
nvidia-nvtx-cu12==12.1.105


Thanks in advance!

**Comment by Tcc0403** [comment]
Oh I got the error with liger v0.2.1. 
I was testing on main branch instead, so liger-kernel-nightly should fix the problem.
It looks like a casting issue causing the error in addmm, I haven't digged into it, just a guess.
## lastest main branch (nightly)
```bash
❯ git checkout main
Previous HEAD position was e5d6ad7 bump patch ver (#171)
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
❯ python3 peft_bnbs_liger.py
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
`low_cpu_mem_usage` was None, now set to True since model is quantized.
/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:292: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
{'train_runtime': 77.143, 'train_samples_per_second': 3.111, 'train_steps_per_second': 0.389, 'train_loss': 3.4927942911783854, 'epoch': 0.01}
100%|████████████████████████████████████████████████████████████████████████████████| 30/30 [01:17<00:00,  2.57s/it]
```
## v0.2.1
```bash
❯ git checkout v0.2.1
Note: switching to 'v0.2.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e5d6ad7 bump patch ver (#171)
❯ code .
❯ python3 peft_bnbs_liger.py
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
`low_cpu_mem_usage` was None, now set to True since model is quantized.
/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:292: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
  0%|                                                                                  | 0/30 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/tcc/Liger-Kernel/peft_bnbs_liger.py", line 67, in <module>
    trainer_stats = trainer.train()
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 450, in train
    output = super().train(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 3363, in compute_loss
    outputs = model(**inputs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 820, in forward
    return model_forward(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 808, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/peft/peft_model.py", line 1577, in forward
    return self.base_model(
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 188, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/src/liger_kernel/transformers/model/qwen2.py", line 108, in lce_forward
    loss = lce(self.lm_head.weight, shift_hidden_states, shift_labels)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tcc/Liger-Kernel/src/liger_kernel/transformers/fused_linear_cross_entropy.py", line 13, in forward
    return LigerFusedLinearCrossEntropyFunction.apply(
  File "/home/tcc/Liger-Kernel/.venv/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/tcc/Liger-Kernel/src/liger_kernel/ops/fused_linear_cross_entropy.py", line 117, in forward
    torch.addmm(
RuntimeError: self and mat2 must have the same dtype, but got Half and Float
  0%|          | 0/30 [00:03<?, ?it/s]
```
my environment
```bash
❯ pip freeze | grep -e peft -e accelerate -e bitsandbytes -e trl -e nvidia
accelerate==0.34.2
bitsandbytes==0.43.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
peft==0.12.0
trl==0.10.1
```

**Comment by Tcc0403** [comment]
Ok, I did some tests. 
The current `fused_linear_cross_entropy_forward` doesn't check the dtypes of `_input` and `weight`, and doesn't upcast when dtype mismatch. 
The only reason why liger-nightly could work with this gist is because `weight.requires_grad == False` in this case. Thus, it skips the `torch.addmm` block.

**Comment by GianottiGustavo** [comment]
Thanks so much! Setting bf16=False and f16=True worked perfectly!

I truly appreciate all your help!

Do you have any other advice? Should I go ahead and close this issue, or is there something else I should do? Should I try modifying the code in a PR to make it work? (Though I'm not sure if I’ll be able to do so.)

**Comment by GianottiGustavo** [comment]
I wanted to share an observation that might be worth noting.

When training a model on my GPU, I noticed that setting bf16=False and f16=True significantly increases the training time—it takes twice as long compared to other configurations. For the Liger model, using bf16=False and f16=True it results in the same doubled training time as when Liger is not used. In contrast, setting bf16=True and f16=False provides much faster performance.

Here's a breakdown of my observations:
    bf16=False, f16=True with Liger Kernel: 6 hours per epoch
    bf16=False, f16=True without Liger Kernel: 6 hours per epoch
    bf16=True, f16=False without Liger Kernel: 3 hours per epoch



![Screenshot from 2024-09-12 13-51-51](https://github.com/user-attachments/assets/f819a350-39b1-4f80-a3cf-aa5a79e29075)
![Screenshot from 2024-09-12 13-54-04](https://github.com/user-attachments/assets/e03366f0-c7cb-4629-9adb-bffd825d7316)

**Comment by Tcc0403** [comment]
Thanks for your sharing. 

Let me conclude some issues that current liger-kernel has:
1. In lce_foward() for monkey_patch, [hidden states](https://github.com/linkedin/Liger-Kernel/blob/3d0653b035222cbb845435a1994854e4fd219107/src/liger_kernel/transformers/model/qwen2.py#L104) are upcasted to float32 from bfloat16 (no upcast with float16), which may cause dtype mismatch error in flce.
2. [weight](https://github.com/linkedin/Liger-Kernel/blob/3d0653b035222cbb845435a1994854e4fd219107/src/liger_kernel/ops/fused_linear_cross_entropy.py#L41) (hidden_state of the model) is not trainable in this [example](https://gist.github.com/Tcc0403/9cbe9a0c9c957a127494dd754c57e568), since the [`torch.addmm`](https://github.com/linkedin/Liger-Kernel/blob/3d0653b035222cbb845435a1994854e4fd219107/src/liger_kernel/ops/fused_linear_cross_entropy.py#L108) block is skipped. 

@ByronHsu What should we do next?

**Comment by GianottiGustavo** [comment]
@Tcc0403 
For point 2, I was wondering if the issue might be related to the fact that I’m using LoRA adapters to train. My understanding is that when using LoRA, only the adapter parameters should be updated, and not the main model weights. So, I think that this behavior is expected.

Could this be why the weight isn’t trainable in this case? Or am I missing something important here?

**Comment by Tcc0403** [comment]
@GianottiGustavo You're right, I totally forgot we're training with LoRA. Thanks for your reminder.
I'll do a quick test to make sure weight is trainable without LoRA, then update the comment.

**Comment by GianottiGustavo** [comment]
@Tcc0403 Some updates on my end:
I changed "liger_kernel/ops/fused_linear_cross_entropy.py" and now works with 
bf16=True, f16=False with Liger Kernel



The code change is not clean at all, and changes have to be made to the bias as well. However, take a look:
```
import torch
import triton

from liger_kernel.ops.cross_entropy import element_mul, liger_cross_entropy_kernel

# The hard limit of TRITON_MAX_TENSOR_NUMEL is 1048576 https://github.com/triton-lang/triton/blob/ba42a5c68fd0505f8c42f4202d53be0f8d9a5fe0/python/triton/language/core.py#L19
# However, setting limit as 65536 as in LayerNorm tutorial is faster because of less register spilling
# The optimal maximum block size depends on your hardware, your kernel, and your dtype
MAX_FUSED_SIZE = 65536 // 2


class LigerFusedLinearCrossEntropyFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, _input, weight, target, bias=None, ignore_index=-100):
        """
        Fusing the last linear layer with cross-entropy loss
            Reference: https://github.com/mgmalek/efficient_cross_entropy

        Handle the forward and backward pass of the final linear layer via cross-entropy loss by avoiding
        the materialization of the large logits tensor. Since Cross Entropy Loss is the last layer, we can
        compute the gradient at the forward pass. By doing so, we don't have to store the _input and target
        for the backward pass.

        _input: (B*T, H) where B is batch size, T is sequence length, H is hidden dimension.
        target: (B*T) where each value is in [0, V-1]
        weight: (V, H) where V is the number of classes
        bias: (V) where V is the number of classes
        ignore_index: the index to ignore in the target
        """
        dtype = (
            torch.get_autocast_gpu_dtype()
            if torch.is_autocast_enabled()
            else _input.dtype
        )
        device = _input.device

        # inputs have shape: BT x H
        # materialized activations will have shape: BT x V
        # the increase in memory = BT x V
        # reduction can be achieved by partitioning the number of tokens BT into smaller chunks.
        # for ex: if we were to achieve the same memory consumption as BT x H, then the chunk size should be:
        # inc_factor = (V+H-1)//H, chunk_size = (BT + inc_factor - 1)//inc_factor
        # for ex: BT = 4096*4, V = 32000, H = 4096 ==> inc_factor = 8, chunk_size = 2048
        BT, H = _input.shape
        V = weight.shape[0]
        BLOCK_SIZE = min(MAX_FUSED_SIZE, triton.next_power_of_2(V))

        inc_factor = triton.cdiv(V, H)  # (V + H - 1) // H
        chunk_size = triton.next_power_of_2(
            triton.cdiv(BT, inc_factor)
        )  # (BT + inc_factor - 1) // inc_factor
        num_chunks = triton.cdiv(BT, chunk_size)  # (BT + chunk_size - 1) // chunk_size

        grad_weight = torch.zeros_like(weight, device=device)
        grad_input = torch.zeros_like(_input, device=device)
        grad_bias = torch.zeros_like(bias, device=device) if bias is not None else None
        # we use fp32 for loss accumulator
        loss_1d = torch.zeros(BT, dtype=torch.float32, device=device)

        total_n_non_ignore = (target != ignore_index).sum().item()

        for chunk_id in range(num_chunks):
            start_idx = chunk_id * chunk_size
            end_idx = min((chunk_id + 1) * chunk_size, BT)
            _input_chunk = _input[start_idx:end_idx]  # chunk_size x H

            # when doing matmul, use the original precision
            logits_chunk = _input_chunk @ weight.t()  # chunk_size x V
            if bias is not None:
                logits_chunk = logits_chunk + bias
            target_chunk = target[start_idx:end_idx]  # chunk_size,

            n_rows = logits_chunk.shape[0]

            # unreduced loss
            loss_1d_slice = loss_1d[start_idx:end_idx]  # chunk_size,
            n_non_ignore = (target_chunk != ignore_index).sum().item()

            # when doing CE, use the upcasted precision
            logits_chunk = logits_chunk.float()

            # ensure _input and target are contiguous
            logits_chunk = logits_chunk.contiguous()
            target_chunk = target_chunk.contiguous()

            # Here we calculate the gradient of logits_chunk in place so we can save memory.
            liger_cross_entropy_kernel[(n_rows,)](
                X_ptr=logits_chunk,
                X_stride=logits_chunk.stride(-2),
                Y_ptr=target_chunk,
                Y_stride=target_chunk.stride(-1),  # always 1
                loss_ptr=loss_1d_slice,
                loss_stride=loss_1d_slice.stride(-1),  # always 1
                n_cols=V,
                n_non_ignore=n_non_ignore,
                ignore_index=ignore_index,
                BLOCK_SIZE=BLOCK_SIZE,
                num_warps=32,
            )

            # gradient of logits_chunk is computed in-place by the above triton kernel.
            # Following HuggingFace model source code, we do the forward and backward
            # w.r.t. logits in fp32 for numerical stability especially as the num classes (vocab size) os huge.
            # (reference: https://github.com/huggingface/transformers/blob/v4.42.4/src/transformers/models/llama/modeling_llama.py#L1194)
            # Propagating to lm_head's backward, we'll switch back to the original dtype.
            logits_chunk = logits_chunk.to(dtype)

            # gradient of logits_chunk is computed in-place by the above triton kernel and is of shape: chunk_size x V
            # thus grad_input[start_idx: end_idx] should be of shape: chunk_size x H
            # additionally, since we are chunking the inputs, observe that the loss and gradients are calculated only
            # on `n_non_ignore` tokens. However, the gradient of the input should be calculated for all tokens.
            # Thus, we need an additional scaling factor of (n_non_ignore/total_n_non_ignore) to scale the gradients.
            grad_logits_chunk = logits_chunk * (
                n_non_ignore / total_n_non_ignore
            )  # chunk_size x V
            grad_input[start_idx:end_idx] = grad_logits_chunk @ weight
            grad_weight = grad_weight.to(dtype)
            _input_chunk = _input_chunk.to(dtype)
            torch.addmm(
                input=grad_weight,
                mat1=logits_chunk.t(),
                mat2=_input_chunk,
                out=grad_weight,
                alpha=n_non_ignore / total_n_non_ignore,
                beta=1.0,
            )

            if bias is not None:
                torch.add(
                    input=grad_bias,
                    other=logits_chunk.sum(dim=0),
                    out=grad_bias,
                    alpha=n_non_ignore / total_n_non_ignore,
                )

        loss = torch.sum(loss_1d) / total_n_non_ignore

        # downcast to dtype and store for backward
        ctx.save_for_backward(
            grad_input.detach(),
            grad_weight.detach(),
            grad_bias.detach() if bias is not None else None,
        )
        return loss

    @staticmethod
    def backward(ctx, grad_output):
        (grad_input, grad_weight, grad_bias) = ctx.saved_tensors

        # Check if grad_weight.dtype is compatible with the current GPU
        if is_dtype_compatible(grad_weight.dtype):
            compatible_dtype = grad_weight.dtype
        elif is_dtype_compatible(torch.float16):
            compatible_dtype = torch.float16
        else:
            compatible_dtype = torch.float32

        grad_input = grad_input.to(compatible_dtype)
        grad_output = grad_output.to(compatible_dtype)
        grad_weight = grad_weight.to(compatible_dtype)

        # If cross entropy is the last layer, grad_output is 1.0. Skip the mul to save time
        if torch.ne(grad_output, torch.tensor(1.0, device=grad_output.device)):
            # We use a Triton kernel instead of a PyTorch operation because modifying inputs in-place
            # for gradient storage and backward multiple times causes anomalies with PyTorch but not with Triton.
            BT, H = grad_input.shape
            n_rows = BT
            BLOCK_SIZE = min(MAX_FUSED_SIZE, triton.next_power_of_2(H))

            element_mul[(n_rows,)](
                grad_input,
                grad_input.stride(-2),
                grad_output,
                H,
                BLOCK_SIZE=BLOCK_SIZE,
                num_warps=32,
            )

            # handle grad_weight
            V, H = grad_weight.shape
            n_rows = V
        
            element_mul[(n_rows,)](
                grad_weight,
                grad_weight.stride(-2),
                grad_output,
                H,
                BLOCK_SIZE=BLOCK_SIZE,
                num_warps=32,
            )

            if grad_bias is not None:
                V = grad_bias.shape[0]
                n_rows = V

                element_mul[(n_rows,)](
                    grad_bias,
                    grad_bias.stride(-1),
                    grad_output,
                    1,
                    BLOCK_SIZE=BLOCK_SIZE,
                    num_warps=32,
                )

        return (grad_input, grad_weight, None, grad_bias, None)


def is_dtype_compatible(dtype):
    # Check the compute capability of the GPU
    compute_capability = torch.cuda.get_device_capability(0)
    major, minor = compute_capability

    # Determine if the dtype is compatible with the current GPU
    if dtype == torch.bfloat16 and major >= 8:
        return True  # bfloat16 is supported on GPUs with compute capability 8.0 or higher
    elif dtype == torch.float16 and major >= 7:
        return True  # float16 is supported on GPUs with compute capability 7.0 or higher
    elif dtype == torch.float32:
        return True  # float32 is universally supported
    else:
        return False
```

Like this works!

I'm happy with the result.
Comparison with 1 epoch, imdb dataset, with "PrunaAI/HuggingFaceTB-SmolLM-135M-Instruct-bnb-4bit-smashed", PEFT on my 1060 (f16 compatible, no bf16 compatible):

- bf16=False, fp16=True with Liger Kernel: estimated 10 hours per epoch, max 2228MiB VRAM
- bf16=False, fp16=True without Liger Kernel: estimated 7:30 hours per epoch, max 3002MiB VRAM
- - 
- bf16=True, fp16=False with Liger Kernel: estimated 4:40 hours per epoch, max 2938MiB VRAM
- bf16=True, fp16=False without Liger Kernel: estimated 2:30 hours per epoch, max 3726MiB VRAM

Again, I'm really happy with the result.

The memory footprint can be even lower with a bf16-compatible GPU.

**Comment by Tcc0403** [comment]
Nice work, there's an analysis about triton kernel's type promotion in #238.

The main reason of mismatch is the [casting](https://github.com/linkedin/Liger-Kernel/blob/d4879dfe2974d2a4d85019f143c331709f6920f5/src/liger_kernel/ops/fused_linear_cross_entropy.py#L96) after kernel computation, a simple remove could avoid the error, so I think we don't need compatible_dtype checks in liger_kernel side which would potentially be overhead. 

It seems this bug will be fixed with the PR mentioned above, but feel free to send a PR if you get any solutions!

**Comment by GianottiGustavo** [comment]
I will just close the issue, since installing from main remove my issue.

Thx for all the support!

**Comment by kostum123** [comment]
This issue still exist on main.

**Comment by Tcc0403** [comment]
@kostum123 could you describe the bug? Is it still dtype mismatch at addmm with bfloat16?

**Comment by kostum123** [comment]
> @kostum123 could you describe the bug? Is it still dtype mismatch at addmm with bfloat16?

Yes, but while full ft. models llama3.2 3b and qwen2.5 3b https://github.com/hiyouga/LLaMA-Factory/issues/5583

**Comment by Tcc0403** [comment]
https://github.com/linkedin/Liger-Kernel/blob/8e2bd26f67123d37333488206fb8f36614c9567c/src/liger_kernel/ops/fused_linear_cross_entropy.py#L103

@kostum123 comment this line for a quick fix. #238 will fix this issue too.

**Comment by kostum123** [comment]
> https://github.com/linkedin/Liger-Kernel/blob/8e2bd26f67123d37333488206fb8f36614c9567c/src/liger_kernel/ops/fused_linear_cross_entropy.py#L103
> 
> @kostum123 comment this line for a quick fix. #238 will fix this issue too.

Thank you for pointing that out. Currently, Liger kernel is broken on main and the project doesn't seem properly supported by LinkedIn. It takes too long for PRs to merge, even for simple fixes, which can take weeks. I think the team is small for this project but that could improve by letting trusted community members merge PRs. I hope we see faster action for small yet critical issues.
